services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BINARY_NAME: tg-relay-rs
    environment:
      TELOXIDE_TOKEN: ${TELOXIDE_TOKEN}
      YTDLP_FORMAT: ${YTDLP_FORMAT:-best}
      COOKIES_PATH: /app/yt-cookies.txt
      RUST_LOG: ${RUST_LOG:-info}
    restart: unless-stopped
    volumes:
      - ./comments.txt:/app/comments.txt:ro
      - /etc/secrets/yt-cookies.txt:/app/yt-cookies.txt:rw
