services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BINARY_NAME: tg-relay-rs
    environment:
      TELOXIDE_TOKEN: ${TELOXIDE_TOKEN}
      COOKIES_PATH: /app/yt-cookies.txt
      RUST_LOG: ${RUST_LOG:-info}
    restart: unless-stopped
    # If you need persistent storage (e.g. caching):
    volumes:
      - ./comments.txt:/app/comments.txt:ro
      - ~/.config/yt-cookies.txt:/app/yt-cookies.txt:ro
