services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BINARY_NAME: tg-relay-rs
    env_file: .env
    environment:
      IG_SESSION_COOKIE_PATH: /app/instagram.txt
      TIKTOK_SESSION_COOKIE_PATH: /app/tiktok.txt
      TWITTER_SESSION_COOKIE_PATH: /app/twitter.txt
      YOUTUBE_SESSION_COOKIE_PATH: /app/youtube.txt
    restart: unless-stopped
    volumes:
      - ./comments.txt:/app/comments.txt:ro
      - ${IG_SESSION_COOKIE_PATH:-/etc/secrets/www.instagram.com_cookies.txt}:/app/instagram.txt:rw
      - ${TIKTOK_SESSION_COOKIE_PATH:-/etc/secrets/www.tiktok.com_cookies.txt}:/app/tiktok.txt:rw
      - ${TWITTER_SESSION_COOKIE_PATH:-/etc/secrets/www.twitter.com_cookies.txt}:/app/twitter.txt:rw
      - ${YOUTUBE_SESSION_COOKIE_PATH:-/etc/secrets/www.youtube.com_cookies.txt}:/app/youtube.txt:rw
